logo: "https://raw.githubusercontent.com/PEAKE-Technology-Partners/public-docs/main/assets/peake_logoDARK.jpg"
description: A Public Blog, where we can post content and tutorials.
remote_theme: "pmarsceill/just-the-docs"
color_scheme: dark

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


callouts:
  warning:
    title: Warning
    color: red



#theme: just-the-docs

url: https://peake-technology-partners.github.io/public-docs

aux_links:
  "PEAKE Home Page":
    - "https://peaketechnology.com"

aux_links_new_tab: true


